server:
  port: 8080

spring:
  application:
    name: order-platform
  cache:
    type: redis
    redis:
      time-to-live: PT5M
  data:
    redis:
      host: localhost
      port: 6379

aws:
  region: us-east-1
  dynamodb:
    endpoint: http://localhost:8000
    tableName: Orders
    customerTableName: Customers
  sns:
    endpoint: http://localhost:4566
    topicName: order-events
  sqs:
    endpoint: http://localhost:4566
    processorQueueName: order-processor-queue
    lambdaQueueName: order-lambda-queue
    emailQueueName: order-email-queue
    smsQueueName: order-sms-queue
    shippingQueueName: order-shipping-queue
    pollIntervalMs: 5000
  ses:
    endpoint: http://localhost:4566
    senderEmail: no-reply@example.com
  currency: AED
  accessKeyId: local
  secretAccessKey: local
